services:
  scanner:
    container_name: ix500-scanner
    image: kalutes/ix500-scan-on-button:latest
    restart: "always"
    privileged: true
    volumes:
      - /mnt/CloudBackup/BackedUpFiles/paperless-ingest:/scans
